Update publish_npm.yml

diff --git a/.github/workflows/publish_npm.yml b/.github/workflows/publish_npm.yml
--- a/.github/workflows/publish_npm.yml
+++ b/.github/workflows/publish_npm.yml
@@ -22,4 +22,5 @@ jobs:
           NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
         run: |
           echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
-          npm run publish.all
+          # run publish in every package, ignore failures (ie no publish required if the version is already published)
+          lerna exec --no-bail --stream --concurrency 1 -- "cp ../../.npmrc . && (npm publish || true)"
